ktor:
  deployment:
    port: 10000
    host: 0.0.0.0
  application:
    modules:
      - com.example.ApplicationKt.module

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: ${JDBC_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}